# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Will Smith's Blog
email: will@willsmith.rocks
description: > # this means to ignore newlines until "baseurl:"
  My blog covering everything from writing code, admining systems,
  to network engineering, and anything I feel like writing about.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://willsmith.rocks" # the base hostname & protocol for your site
twitter_username: individuwill
github_username:  individuwill

# Build settings
markdown: kramdown
